-- Briefings, reminders and Web Push.
-- settings: key/value (times, timezone, last-sent dates, last notice, VAPID keys).
--   The VAPID private key lives here, generated by the Worker on first use. This
--   database is private to the account and no API route ever returns it.
CREATE TABLE settings (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL
);

-- One row per device that enabled notifications.
CREATE TABLE push_subscriptions (
  endpoint TEXT PRIMARY KEY,
  subscription TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);
